model = "gpt-5.2-codex"
model_reasoning_effort = "medium"
tool_output_token_limit = 25000
model_auto_compact_token_limit = 233000

[projects."/Users/gursh/code"]
trust_level = "trusted"

[projects."/Users/gursh/code/halo"]
trust_level = "trusted"

[projects."/Users/gursh/code/creator-operations"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

[features]
ghost_commit = false
unified_exec = true
apply_patch_freeform = true
web_search_request = true
skills = true
shell_snapshot = true
rmcp_client = true
steer = true

[mcp_servers.nia]
url = "https://apigcp.trynia.ai/mcp"
startup_timeout_sec = 30
tool_timeout_sec = 360
bearer_token_env_var = "NIA_TOKEN"

[mcp_servers.posthog]
url = "https://mcp.posthog.com/mcp"
bearer_token_env_var = "POSTHOG_TOKEN"

[otel]
environment = "prod"
log_user_prompt = true

[otel.exporter.otlp-http]
endpoint_env_var = "OTEL_ENDPOINT"
protocol = "binary"
